"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nqxx+o04w1$f7mfp+)74xj!oi1$v%vb7@sq@f%@2vw=^)d!k)@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['3.110.143.60', 'pirlanta.in', 'www.pirlanta.in', '127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = [
    'https://3.110.143.60',
    'https://pirlanta.in',
    'https://www.pirlanta.in',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://localhost',
    'http://localhost:8000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'website',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'website' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Use PostgreSQL in production. Configure via environment variables.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (SMTP)
# Set EMAIL_BACKEND to 'django.core.mail.backends.console.EmailBackend' to print emails to console (for debugging)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'nidhi@pirlanta.in'
EMAIL_HOST_PASSWORD = 'fftmdkuciijxnglf'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



OTX_API_KEY="89002c1dad4699ad93d01f43f392b6f0b556d0b9994144f33f1c1f15d768221c"
ABUSEIPDB_API_KEY="d7e9cf20dc59779fb98986ffccecbbb9ee0d03987ca59ac80ed5c28f02f0c0c06b45c850b58f7181"
THREATMAP_CACHE_SECONDS=300
THREATMAP_MAX_EVENTS=50
THREATMAP_TARGET_LAT=20.5937
THREATMAP_TARGET_LNG=78.9629
THREATMAP_TARGET_CITY="New Delhi"
THREATMAP_TARGET_COUNTRY="India"
THREATMAP_DENSITY_MULTIPLIER=2
THREATMAP_JITTER_DEGREES=0.6
THREATMAP_RESPONSE_BUDGET_SECONDS = 18
THREATMAP_FEED_TIMEOUT_SECONDS = 15
THREATMAP_GEO_TIMEOUT_SECONDS = 3
THREATMAP_WS_INTERVAL_SECONDS = 5


URLHAUS_TEXT_ONLINE_URL=""
THREATFOX_IPPORT_RECENT_URL="https://threatfox.abuse.ch/export/json/ip-port/recent/"
FEODO_IP_BLOCKLIST_URL="https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt"

# Assessment redirect - set to your deployed digital-assessment URL (e.g. Netlify, Vercel)
ASSESSMENT_REDIRECT_URL = os.environ.get("ASSESSMENT_REDIRECT_URL", "")

# Logging - show assessment report errors in console
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "website": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
